# Generated by Django 5.2.15 on 2026-08-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_public',
        ),
        migrations.AddField(
            model_name='file',
            name='share_type',
            field=models.CharField(choices=[('none', 'Paylaşılmayıb'), ('public', 'Hesabsız (ictimai)'), ('account', 'Yalnız hesablı')], default='none', max_length=10),
        ),
    ]
