# Generated by Django 5.2.15 on 2026-08-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_comment_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ad_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
